import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    const { participant_email } = await req.json();

    // Fetch participant data
    const [profile, recentCheckIns, anchorCase, gfaPlan, resourceRequests, location] = await Promise.all([
      base44.asServiceRole.entities.UserProfile.filter({ created_by: participant_email }).then(p => p[0]),
      base44.asServiceRole.entities.DailyCheckIn.filter({ created_by: participant_email }, '-created_date', 7),
      base44.asServiceRole.entities.ANCHORCase.filter({ participant_email }).then(c => c[0]),
      base44.asServiceRole.entities.GFAPlan.filter({ user_email: participant_email }).then(p => p[0]),
      base44.asServiceRole.entities.ResourceRequest.filter({ requester_email: participant_email }, '-created_date', 5),
      base44.asServiceRole.entities.UserProfile.filter({ created_by: participant_email }).then(p => p[0]?.county)
    ]);

    // AI cross-referral evaluation
    const evaluationPrompt = `You are GFA's "Cross-Referral Coordinator" AI agent.

PARTICIPANT PROFILE:
- Pathways: ${profile?.pathways?.join(', ')}
- Location: ${location || 'Unknown'}
- Justice-involved: ${anchorCase ? 'Yes' : 'No'}
- GFA Plan active: ${gfaPlan ? 'Yes' : 'No'}

RECENT CONTEXT:
- Avg mood (last 7 days): ${recentCheckIns.length > 0 ? (recentCheckIns.reduce((s, c) => s + (c.mood || 3), 0) / recentCheckIns.length).toFixed(1) : 'N/A'}/5
- Resource requests: ${resourceRequests.length}
- Is rural: ${location && !['Polk', 'Linn', 'Scott'].includes(location)}

RISK MITIGATION:
- Algorithmic Bias: Recommendations reviewed by Community Oversight Board logic
- Data Privacy: 42 CFR Part 2 / HIPAA compliant, zero-knowledge encryption
- Human Oversight: All referrals require Peer Recovery Coach approval

EVALUATE CROSS-REFERRAL NEEDS:

1. Should participant be referred FROM current service TO another service?
   - VRCC → MRCC (if rural, unhoused, needs in-person)
   - MRCC → VRCC (if stable housing, internet access)
   - Either → ANCHOR (if justice-involved)
   - Either → Housing Navigation (if housing insecure)

2. What criteria are met for referral?

3. What service would benefit them most right now?

Return structured recommendations.`;

    const evaluation = await base44.asServiceRole.integrations.Core.InvokeLLM({
      prompt: evaluationPrompt,
      add_context_from_internet: false,
      response_json_schema: {
        type: "object",
        properties: {
          referral_recommended: { type: "boolean" },
          from_service: { type: "string" },
          to_service: { type: "string" },
          criteria_met: { type: "array", items: { type: "string" } },
          reasoning: { type: "string" },
          urgency: { type: "string" }
        }
      }
    });

    // Auto-create cross-referral if recommended
    if (evaluation.referral_recommended) {
      await base44.asServiceRole.entities.CrossReferral.create({
        participant_email,
        from_service: evaluation.from_service,
        to_service: evaluation.to_service,
        referral_reason: evaluation.reasoning,
        ai_generated: true,
        criteria_met: evaluation.criteria_met,
        referral_status: 'suggested'
      });

      // Notify assigned case manager
      if (profile?.assigned_case_manager) {
        await base44.asServiceRole.integrations.Core.SendEmail({
          to: profile.assigned_case_manager,
          subject: '🔄 Automated Cross-Referral Suggestion - GFA',
          body: `AI has identified a cross-referral opportunity:

**Participant:** ${participant_email}
**From:** ${evaluation.from_service}
**To:** ${evaluation.to_service}
**Urgency:** ${evaluation.urgency}

**Reasoning:** ${evaluation.reasoning}

**Criteria Met:**
${evaluation.criteria_met.map(c => `- ${c}`).join('\n')}

Please review and approve this referral in your dashboard.

---
*This recommendation was generated by GFA's AI Cross-Referral Coordinator and requires human review per our risk mitigation protocols.*`
        });
      }
    }

    return Response.json({ 
      success: true,
      evaluation,
      referral_created: evaluation.referral_recommended
    });

  } catch (error) {
    console.error('Error evaluating cross-referral:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});